import "./globals.css";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import QueryProviders from "@/providers/QueryProviders";
import Providers from "@/providers/Providers";

export const metadata = {
  title: "Hotel And Bus Bokking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <QueryProviders>
            <main className="min-h-screen bg-[#f0f0f0bb]">
              {children}
              <ToastContainer
                position="bottom-right"
                autoClose={1500}
                transition={Slide}
                closeOnClick
              />
            </main>
          </QueryProviders>
        </Providers>
      </body>
    </html>
  );
}
